version: '2'
services:
  # phpMyAdmin をデフォルトで起動する
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6.3-3
    ports:
      - "8000:80"
    environment:
      # MySQL サーバのアドレス（ホストのアドレスを指定する）
      PMA_HOST: 172.17.0.1
